// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Solitons.CommandLine
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    internal partial class CliGeneralHelpRtt : Solitons.Text.RuntimeTextTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
 if(!string.IsNullOrWhiteSpace(Logo))WriteLine(Logo); 
            this.Write(this.ToStringHelper.ToStringWithCulture(Description));
            this.Write("\r\n\r\nUsage:\r\n  ");
            this.Write(this.ToStringHelper.ToStringWithCulture(ProgramName));
            this.Write(" [command] [options]\r\n\r\nAvailable Commands:  ");
 foreach(var cmd in Commands){ 
            this.Write(" \r\n    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(cmd.Synopsis.PadRight(SynopsisWidth)));
            this.Write(" ");
            this.Write(this.ToStringHelper.ToStringWithCulture(cmd.Description));
            this.Write("\r\n  ");
 } 
            this.Write(" \r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
