// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Solitons.CommandLine
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    internal partial class CliHelpRtt : Solitons.Text.RuntimeTextTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(this.ToStringHelper.ToStringWithCulture(Logo));
            this.Write("\r\nUsage: COMMAND [ARGS] [OPTIONS]\r\n\r\nDescription:\r\n  ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Description));
            this.Write("\r\n\r\nOptions:\r\n  -h, --help  Show this message and exit.\r\n\r\nCommands:");
 foreach(var cmd in Commands){ 
            this.Write(" \r\n\r\n  ");
            this.Write(this.ToStringHelper.ToStringWithCulture(cmd.Path));
            this.Write("        ");
            this.Write(this.ToStringHelper.ToStringWithCulture(cmd.Description));
            this.Write(" ");
 } 
            this.Write(" \r\n\r\nFor detailed information on a specific command, use \'toolname COMMAND --help" +
                    "\'.\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
