// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Solitons.Postgres.PgUp.Formatting
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    internal partial class PgUpTransactionDelimiterRtt : Solitons.Text.RuntimeTextTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("  _____ ___ __  __\r\n |_   _| _ \\\\ \\/ /\r\n   | | |   / >  <   ");
            this.Write(this.ToStringHelper.ToStringWithCulture(DisplayName));
            this.Write(" \r\n   |_| |_|_\\/_/\\_\\");
            return this.GenerationEnvironment.ToString();
        }
    }
}
