// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Solitons.CommandLine.ZapCli
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    internal partial class ZapCliPropertyBundleRegexRtt : Solitons.Text.RuntimeTextTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("(?xim-s)\r\n(?: \r\n  \\s*\r\n   (?:");
 foreach(var parameter in Parameters){ 
            this.Write(" \r\n     (?: ");
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Pattern));
            this.Write(" ) | ");
 } 
            this.Write("  \r\n     \\S+ # Unrecognized token\r\n   )\r\n)*\r\n\r\n\r\n\r\n\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
