// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Solitons.Postgres.PgUp
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    internal partial class PgUpConnectionDisplayRtt : Solitons.Text.RuntimeTextTemplate
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("host:     ");
            this.Write(this.ToStringHelper.ToStringWithCulture(_builder.Host));
            this.Write(":");
            this.Write(this.ToStringHelper.ToStringWithCulture(_builder.Port));
            this.Write("\r\ndatabase: ");
            this.Write(this.ToStringHelper.ToStringWithCulture(_builder.Database));
            this.Write("\r\nusername: ");
            this.Write(this.ToStringHelper.ToStringWithCulture(_builder.Username));
            return this.GenerationEnvironment.ToString();
        }
    }
}
