name: DEV:Solitons

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]



env:
  POSTGRES_CONNECTION: ${{ secrets.SOLITONS_TEST_POSTGRES_SERVER_CONNECTION_STRING }}
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  STAGING_TYPE: Alpha

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and Publish to NuGet
      shell: pwsh
      run: |
        docker build -t solitons-build `
          --build-arg STAGING_TYPE=${{ env.STAGING_TYPE }} `
          --build-arg SOLITONS_TEST_POSTGRES_SERVER_CONNECTION_STRING="${{ env.POSTGRES_CONNECTION }}" `
          --build-arg NUGET_API_KEY="${{ env.NUGET_API_KEY }}" `
          .