name: .NET CI/CD for Solitons.SQLite

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      solutionpath: ./solitons.sln
      sqlitecsproj: ./src/Solitons.SQLite/Solitons.SQLite.csproj
      buildconfiguration: release
      outputpath: pkgout
      runId: ${{github.run_id}}
      nugetsource: https://api.nuget.org/v3/index.json
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Cache NuGet packages
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: nuget-

    - name: Restore dependencies
      run: dotnet restore ${{env.solutionpath}}

    - name: Build
      run: dotnet build ${{env.solutionpath}} --no-restore --configuration ${{env.buildconfiguration}}

    - name: Test
      run: dotnet test ${{env.solutionpath}} --no-build --verbosity normal

    - name: Pack
      env:
        versionsuffix: 'alpha.${{env.runId}}'
      run: dotnet pack ${{env.sqlitecsproj}} --configuration ${{env.buildconfiguration}} --output ${{env.outputpath}} --version-suffix ${{env.versionsuffix}} --no-build --no-restore

    - name: Push to NuGet
      env:
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
      run: dotnet nuget push ${{env.outputpath}}/*.nupkg --api-key ${{env.NUGET_API_KEY}} --source ${{env.nugetsource}} --skip-duplicate
