name: Unlist Pre-releases

on:
  push:
    branches: [ develop, preview, main ]
  pull_request:
    branches: [ ]



env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
jobs:
  unlist:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Unlist
      shell: pwsh
      run: ./build/on-push.ps1   